#Radioactive decay simulation
/control/verbose 0
/control/saveHistory
/run/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 2

/CDEX/sim/set/mode CDEXArParametersTest
/CDEX/src/type CuContainer
/CDEX/run/refresh true

# Initialize kernel
/run/initialize

#Ac228
#Tl208
/gps/particle ion
/gps/ion 81 208 0 0
/gps/energy 0 keV
/run/beamOn 10


